version: '3.0'

include:
  - infra.yml
services:
  main:
    build: .
    # restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: 'db'
    command: 'daphne -b :: ${APP_NAME}.asgi:application'
    expose:
      - '8000'
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - db
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 5050:80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - main

volumes:
  static_volume:
