version: '3.0'

services:
  db:
    image: "postgres:alpine"
    # restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
