# Generated by Django 5.0.6 on 2024-05-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=99999999, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck'),
            preserve_default=False,
        ),
    ]
